services: 
  minio: 
    image: minio/minio:latest
    environment:  
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    ports: 
      - "${MINIO_PORT:-9000}:9000"
    volumes: 
      - minio_data:/data
    restart: unless-stopped
  
volumes: 
  minio_data: